name: App CI

on:
  push:
    branches: [ main, master ]

jobs:
  call-build:
    uses: khanmofis/gfs-workflow-files/.github/workflows/maven-build.yml@main
    with:
      java-version: '21'
      maven-goal: 'verify'

