name: App CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  call-build:
    uses: khanmofis/gfs-workflow-files/.github/workflows/maven-build.yml@main
    with:
      java-version: '21'
      maven-goal: 'verify'
      project-key: 'khanmofis_simple-java-maven-app'
      sonar-token: 'd5878957bf94ab055aa3c3ab4dc31fff9b1aca93'
      sonar-host-url: 'https://sonarcloud.io'
      sonar-org: 'khanmofis'


