name: App CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  call-build:
    uses: khanmofis/gfs-workflow-files/.github/workflows/maven-build.yml@main
    with:
      java-version: '21'
      maven-goal: 'verify'
      project-key: 'simple-maven'
      sonar-token: 'sqp_b0c53264467fe4375f86d9c168a5158b4b124f79'
      sonar-host-url: 'http://localhost:9000'


